Chemistry/Web/ViewModels/VideoLesson/VideoLessonDetailsVM.cs
namespace Web.ViewModels.VideoLesson
{
    public class VideoLessonDetailsVM
    {
        public Core.Entities.VideoLesson VideoLesson { get; set; }
    }
}

Chemistry/Web/ViewModels/VideoLesson/VideoLessonIndexVM.cs
namespace Web.ViewModels.VideoLesson
{
    public class VideoLessonIndexVM
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string CategoryTitle { get; set; }
        public string Title { get; set; }
        public List<string> videoLessonCategories { get; set; }
        public bool IsPaid { get; set; }

        //  public List<Core.Entities.VideoLesson> VideoLesson { get; set; }
    }
}

Chemistry/Web/Controllers/VideoLessonController.cs
using DataAcces.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Services.Abstract;
using Web.ViewModels.VideoLesson;

namespace Web.Controllers
{
    public class VideoLessonController : Controller
    {
        private readonly IVideoLessonService _videoLesson;
        private readonly AppDbContext _appDbContext;

        public VideoLessonController(IVideoLessonService videoLesson,AppDbContext appDbContext)
        {
            _videoLesson = videoLesson;
            _appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var lesson = await _videoLesson.Index();
            if (lesson == null) return View();

            return View(lesson);
        }

        public async Task<IActionResult> LoadMore(int count)
        {
            var lesson = await _appDbContext.VideoLessons.
                                OrderByDescending(v => v.Id)
                                .Include(v => v.Category)
                                .Skip(3*count)
                                .Take(3)
                                .ToListAsync();

            return PartialView("_LessonPartial", lesson);

        }
        public async Task<IActionResult> Details(int id)
        {
            var model = new VideoLessonDetailsVM()
            {
                VideoLesson = await _videoLesson.DetailsAsync(id)
            };
            if (model.VideoLesson == null) return BadRequest();
            return View(model);
        }
        
    }
}

Chemistry/Web/Views/VideoLesson/Details.cshtml
@{
    Layout = null;
}
@using Web.ViewModels.VideoLesson
@model VideoLessonDetailsVM
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/assets/style/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Dərslər</title>
</head>

<body>
    <div class="video-lesson">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-12 col-md-12 col-s-12 col-xs-12">
                    <iframe src="@Model.VideoLesson.Video" width="640" height="480" allow="autoplay" allowfullscreen></iframe>
                </div>
            </div>
        </div>

    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

Chemistry/Web/Views/VideoLesson/Index.cshtml
@using Web.ViewModels.VideoLesson
@model List<VideoLessonIndexVM>

<div id="preloader"></div>
<button class="backToTop" type="button">
    <i class="fas fa-level-up-alt"></i>
</button>

<main class="main-section">
    <section class="allPageHeader">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="newsContent">
                        <h1 title="Dərslər">Dərslər</h1>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <section class="lessonPage">
        <div class="container">
            <div class="filterLesson">
                <p class="my-list">

                    @foreach (var lessonCategory in Model)
                    {
                        foreach (var item in lessonCategory.videoLessonCategories)
                        {

                            <button data-filter="@item.ToUpper()">@item.ToUpper()</button>

                        }
                        break;
                    }
                </p>
            </div>
            <div id="VideoLessons" class="row">
                @foreach (var videolesson in Model)
                {
                    <div class="all-lesson col-12 col-lg-4 col-md-6" data-name="@videolesson.CategoryTitle.ToUpper()">
                        <div class="lesson">
                            <div class="lessonImage">
                                <img src="~/assets/media/@videolesson.ImageUrl" alt="@videolesson.CategoryTitle">
                            </div>
                            @if (videolesson.IsPaid)
                            {
                                <span>Ödənişlidir</span>
                            }
                            <article>
                                <h4 class="lessonKind" title="lesson kind">@videolesson.Title</h4>
                                <div class="detailButton">
                                    @if (videolesson.IsPaid)
                                    {
                                        <a target="_blank" href="https://wa.me/+994558616088">Ətraflı bax</a>
                                    }
                                    else
                                    {
                                        <a asp-action="details" asp-controller="videolesson" asp-route-id="@videolesson.Id" target="_blank">Ətraflı bax</a>
                                    }
                                </div>
                            </article>

                        </div>

                    </div>
                }

            </div>
            @* <div class="loadMore">
            <button class="loadmore btn btn-primary">Load more</button>
            </div>*@
        </div>
    </section>
</main>

<script src="~/javascript/jquery.js"></script>
<script src="~/javascript/bootstrap.bundle.min.js"></script>
<script src="~/javascript/bootstrap.min.js"></script>
<script src="~/javascript/fontawesome.js"></script>
<script src="~/javascript/owl.carousel.min.js"></script>
<script src="~/javascript/script.js"></script>

Chemistry/Web/Views/VideoLesson/LoadMore.cshtml
@using Web.ViewModels.VideoLesson
@model List<VideoLessonIndexVM>

<div id="preloader"></div>
<button class="backToTop" type="button">
    <i class="fas fa-level-up-alt"></i>
</button>

<main class="main-section">
    <section class="allPageHeader">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="newsContent">
                        <h1 title="Dərslər">Dərslər</h1>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <section class="lessonPage">
        <div class="container">
            <div class="filterLesson">
                <p class="my-list">

                    @foreach (var lessonCategory in Model)
                    {
                        foreach (var item in lessonCategory.videoLessonCategories)
                        {

                            <button  data-filter="@item.ToUpper()">@item.ToUpper()</button>

                        }
                        break;
                    }
                </p>
            </div>
            <div class="row">


                @foreach (var videolessoncategory in Model)
                {
                    <div class="all-lesson col-12 col-lg-4 col-md-6" data-name="@videolessoncategory.CategoryTitle.ToUpper()">
                        <div class="lesson">
                            <div class="lessonImage">
                                <img src="~/assets/media/@videolessoncategory.ImageUrl" alt="">
                            </div>
                            <article>
                                <h4 class="lessonKind" title="lesson kind">@videolessoncategory.Title</h4>
                                <div class="detailButton">
                                    <a href="quiz.html" target="_blank">Ətraflı bax</a>
                                </div>
                            </article>

                        </div>

                    </div>
                }

            </div>
            <div class="loadMore">
                <a id="LoadMore" asp-action="LoadMore" asp-controller="VideoLesson">Load more </a>
            </div>
        </div>
    </section>
</main>

<script src="~/javascript/jquery.js"></script>
<script src="~/javascript/bootstrap.bundle.min.js"></script>
<script src="~/javascript/bootstrap.min.js"></script>
<script src="~/javascript/fontawesome.js"></script>
<script src="~/javascript/owl.carousel.min.js"></script>
<script src="~/javascript/script.js"></script>